[package]
name = "day7"
version = "0.1.0"
authors = ["hvj374"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
queues = "1.1.0"